Simcat13/Final-unsu-react

unsu/src/App.js
unsu/src/components/SideBar.js
unsu/src/components/integrated/Notice.js
unsu/src/components/utils/CustomAxios.js

notice 목록 구현(비동기)

---

unsu/src/components/integrated/Notice.js

테이블 hover 추가

---

unsu/src/App.js
unsu/src/components/integrated/Notice.js
unsu/src/components/integrated/NoticeAdd.js
unsu/src/components/integrated/NoticeDetail.js

Yongnam0430

---

unsu/src/components/integrated/admin/Bus.js
unsu/src/components/integrated/admin/Driver.js

driver 수정 및 bus 목록, 등록 구현

---

unsu/src/components/integrated/admin/Bus.js

버스 crud 리액트 구현

---

unsu/src/App.js
unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/admin/Route.js

노선 리액트 구현중

---

unsu/src/components/integrated/admin/Route.js
unsu/src/components/integrated/admin/Terminal.js

하 왜케 안되냐....................................

route 구현중TT

---

unsu/src/components/integrated/admin/Bus.js
unsu/src/components/integrated/admin/Route.js

terminal crud하고 route 삭제 왜 시간은안되냐고진짜

---

unsu/package-lock.json
unsu/package.json
unsu/src/components/integrated/admin/Route.js
unsu/src/components/integrated/admin/Terminal.js
unsu/src/components/utils/Pagination.js

노선ㅋㅋㅋㅋ짜증남ㄴㅋㅋㅋㅋ

---

unsu/src/components/integrated/notice/Notice.js

검색시 페이지네이션 구현 중

---

unsu/src/components/TestKje.js
unsu/src/components/integrated/admin/Route.js
unsu/src/components/integrated/admin/Terminal.js
unsu/src/components/utils/Pagination.js

노선 수정 성공!!!! 시간표출력 되고 ㅋ

---

unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/admin/Route.js

관리자가 채팅, 챗봇 확인가능

---

unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/admin/Charge.js
unsu/src/components/integrated/admin/Route.js

노선 작업중 및 요금관리 생성

---

unsu/src/components/integrated/admin/Bus.js
unsu/src/components/integrated/admin/Charge.js
unsu/src/components/integrated/admin/Terminal.js

요금 crud 하는중

---

unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/admin/Bus.js
unsu/src/components/integrated/admin/Charge.js
unsu/src/components/integrated/admin/Driver.js
unsu/src/components/integrated/admin/MemberList.js
unsu/src/components/integrated/admin/Terminal.js

member 리스트 및 상세 구현중

---

unsu/src/components/integrated/websocket/chatbot.js
unsu/src/components/integrated/websocket/memberChat.js

모든 관리자가 상담채팅 가능, 관리자는 회원목록에 안뜸

---

unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/admin/MemberList.js
unsu/src/components/integrated/admin/PointList.js

포인트를 하고잇는데요 뭘하는건지모르겠네요

---

unsu/package-lock.json
unsu/package.json
unsu/src/components/integrated/review/ReviewList.js

리액트 토큰으로 로그인 아이디 받아오기 구현중

---

unsu/src/components/integrated/websocket/memberChat.js

상대방 화면에 채팅이 실시간으로 갱신되지 않는 문제 발견하여 문제 해결

---

unsu/src/App.js
unsu/src/components/TestPrice.js
unsu/src/components/integrated/admin/PointList.js
unsu/src/components/integrated/member/Mypage.js
unsu/src/components/integrated/member/Point.js

관리자 포인트 리스트 구현 완료 아싸

---

unsu/src/components/integrated/review/ReviewList.js

이용후기 삭제 구현 중

---

unsu/src/components/integrated/notice/Notice.js
unsu/src/components/integrated/review/ReviewList.js

리뷰 관리자만 삭제 버튼 구현

---

unsu/src/components/integrated/admin/PointList.js

아싸~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

포인트 증가 성공~!

---

unsu/src/components/SideBar.js

회원 사이드바 챗봇, 채팅 버튼 수정

---

unsu/src/components/integrated/admin/Bus.js
unsu/src/components/integrated/admin/Charge.js
unsu/src/components/integrated/admin/Driver.js
unsu/src/components/integrated/admin/MemberList.js
unsu/src/components/integrated/admin/PointList.js
unsu/src/components/integrated/admin/Route.js
unsu/src/components/integrated/admin/Terminal.js
unsu/src/components/integrated/member/Point.js
unsu/src/components/utils/Pagination.js

관리자페이지 리액트용 페이징추가

---

unsu/src/components/integrated/notice/Notice.js
unsu/src/components/integrated/notice/NoticeAdd.js
unsu/src/components/integrated/review/ReviewList.js

공지사항, 이용후기 수정

---

unsu/src/components/SideBar.js
unsu/src/components/integrated/websocket/chatbot.css

챗봇 질문 한 줄에 하나씩 나오도록 디자인 수정

---

unsu/src/components/integrated/review/ReviewList.js

리뷰 좋아요 구현 중

---

unsu/src/components/integrated/member/Point.js

포인트 충전 페이지 디자인

---

unsu/src/App.js
unsu/src/components/Home.js
unsu/src/components/SideBar.js
unsu/src/components/integrated/websocket/MemberChat.css
unsu/src/components/integrated/websocket/memberChat.js

챗봇, 채팅 모든화면 모달처리

---

unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/review/ReviewList.js
unsu/src/components/utils/CustomAxios.js

별점 좋아요 구현 완료

---

unsu/src/components/integrated/admin/MemberList.js
unsu/src/components/integrated/admin/ReservationStats.js

회원검색완료, 예약 설명 추가

---

unsu/src/components/integrated/admin/AdminSideBar.js
unsu/src/components/integrated/websocket/chatbot.js

챗봇 클릭시 스크롤 내려주기 구현

---

unsu/src/components/integrated/admin/Bus.js

페이징 수 변경 버스
